<a href="https://colab.research.google.com/github/robsonpiere/ds-minerando-dados-exercicios/blob/master/modulo_05/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy #

In [0]:
#importação da biblioteca
import numpy as np

In [0]:
# criando array de uma dimensão
one_dim = np.array([1,2,3,4])

In [4]:
#exibindo o tipo 
type(one_dim)

numpy.ndarray

In [5]:
#exibindo o número de dimensões
one_dim.ndim

1

In [0]:
#array de duas dimensoes
two_dim = np.array([(1,2,3), (4,5,6)])

In [7]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#valores randomicos
np.random.random((5,2))

array([[0.15929027, 0.40324446],
       [0.84078807, 0.05695366],
       [0.05641524, 0.84104036],
       [0.04013199, 0.19647713],
       [0.05614358, 0.94572577]])

In [12]:
# array esparço de 10 a 50 pulando de 5 em 5
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
#array linear de 0 a 2 no total de 9 elementos
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
# coleção com zeros
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Diferenças entre listas e arrays numpy ##

In [0]:
#ciação de lista
lista = [1,2,3]

In [19]:
lista

[1, 2, 3]

In [18]:
lista * 2

[1, 2, 3, 1, 2, 3]

In [0]:
# conversão de lista pra array numpy
lista = np.array(lista)

In [21]:
type(lista)

numpy.ndarray

In [22]:
lista * 2 

array([2, 4, 6])

In [0]:
#exemplo: Calculo do imc
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [25]:
#vai gerar erro
pesos / altura ** 2

TypeError: ignored

In [0]:
#transformando em numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [28]:
#agora é possível
pesos / altura ** 2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [30]:
#somente valores numericos
a = np.array([1,3, 'Casa', True])
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

In [32]:
#erro ao tentar multiplicar arrays numpy de tipos não numericos
a * 2 

UFuncTypeError: ignored