<a href="https://colab.research.google.com/github/robsonpiere/ds-minerando-dados-exercicios/blob/master/modulo_05/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy #

In [0]:
#importação da biblioteca
import numpy as np

In [0]:
# criando array de uma dimensão
one_dim = np.array([1,2,3,4])

In [3]:
#exibindo o tipo 
type(one_dim)

numpy.ndarray

In [4]:
#exibindo o número de dimensões
one_dim.ndim

1

In [0]:
#array de duas dimensoes
two_dim = np.array([(1,2,3), (4,5,6)])

In [6]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#valores randomicos
np.random.random((5,2))

array([[0.16429184, 0.11066297],
       [0.79651796, 0.13593284],
       [0.8614699 , 0.46985983],
       [0.7505331 , 0.45927349],
       [0.90580808, 0.53903692]])

In [8]:
# array esparço de 10 a 50 pulando de 5 em 5
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
#array linear de 0 a 2 no total de 9 elementos
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
# coleção com zeros
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Diferenças entre listas e arrays numpy ##

In [0]:
#ciação de lista
lista = [1,2,3]

In [12]:
lista

[1, 2, 3]

In [13]:
lista * 2

[1, 2, 3, 1, 2, 3]

In [0]:
# conversão de lista pra array numpy
lista = np.array(lista)

In [15]:
type(lista)

numpy.ndarray

In [16]:
lista * 2 

array([2, 4, 6])

In [0]:
#exemplo: Calculo do imc
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [18]:
#vai gerar erro
pesos / altura ** 2

TypeError: ignored

In [0]:
#transformando em numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [20]:
#agora é possível
pesos / altura ** 2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [21]:
#somente valores numericos
a = np.array([1,3, 'Casa', True])
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

In [22]:
#erro ao tentar multiplicar arrays numpy de tipos não numericos
a * 2 

UFuncTypeError: ignored

## Métodos e atributos ##

In [23]:
#forma do array
two_dim.shape

(2, 3)

In [24]:
#dimensoes
two_dim.ndim

2

In [25]:
# valor máximo
two_dim.max()

6

In [26]:
#valor mínimo
two_dim.min()

1

In [27]:
#media
two_dim.mean()

3.5

In [28]:
#desvio padrão
two_dim.std()

1.707825127659933

In [29]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#tipo de dados
two_dim.dtype

dtype('int64')

In [31]:
#quantidade de elementos
two_dim.size

6

In [32]:
#quantidade em bytes
two_dim.itemsize

8

In [33]:
#somando os elementos array
two_dim.sum()

21

## Transformando Arrays ##


In [34]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#Transposta da matriz
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
#transformar em matriz de uma linha
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [0]:
tree = np.random.random((5,3))

In [39]:
tree

array([[0.64212608, 0.54733708, 0.57081033],
       [0.24722951, 0.2359737 , 0.59114482],
       [0.76560618, 0.13502843, 0.236224  ],
       [0.97682747, 0.11595272, 0.98343822],
       [0.22862462, 0.21719552, 0.23759549]])

In [40]:
tree.shape

(5, 3)

In [41]:
#transformar a matriz em 3 linha e 5 colunas
tree.reshape(3,5)

array([[0.64212608, 0.54733708, 0.57081033, 0.24722951, 0.2359737 ],
       [0.59114482, 0.76560618, 0.13502843, 0.236224  , 0.97682747],
       [0.11595272, 0.98343822, 0.22862462, 0.21719552, 0.23759549]])

In [42]:
#uma linha
tree.reshape(-1)

array([0.64212608, 0.54733708, 0.57081033, 0.24722951, 0.2359737 ,
       0.59114482, 0.76560618, 0.13502843, 0.236224  , 0.97682747,
       0.11595272, 0.98343822, 0.22862462, 0.21719552, 0.23759549])

In [43]:
# uma linha 15 colunas
t = tree.reshape(1,15)
t

array([[0.64212608, 0.54733708, 0.57081033, 0.24722951, 0.2359737 ,
        0.59114482, 0.76560618, 0.13502843, 0.236224  , 0.97682747,
        0.11595272, 0.98343822, 0.22862462, 0.21719552, 0.23759549]])

In [45]:
#adicionando elementos
two_dim = np.insert(two_dim, 0, 10)
two_dim

array([10, 10,  1,  2,  3,  4,  5,  6])

In [47]:
# Removendo elemento
two_dim = np.delete(two_dim, [0])
two_dim

array([1, 2, 3, 4, 5, 6])

In [0]:
# gerando txt
np.savetxt("dataset_numeros.txt", two_dim, delimiter=',')

## Acessando dimensões no Array ##

In [51]:
# array aleatório 10 linhas  e duas colunas
my_array = np.random.random([10,2])
my_array

array([[0.76046086, 0.73266951],
       [0.43396307, 0.79898535],
       [0.8981312 , 0.54180965],
       [0.82887902, 0.55317269],
       [0.60251293, 0.96340895],
       [0.06931808, 0.87787859],
       [0.19855179, 0.91691751],
       [0.98790169, 0.282324  ],
       [0.22151537, 0.71415339],
       [0.40401262, 0.5977481 ]])

In [52]:
# imprimando  primeiro elemento (1 linha)
my_array[0]

array([0.76046086, 0.73266951])

In [53]:
# imprimindo primeiro elemento da 1 coluna
my_array[0][0]

0.7604608618142871

In [54]:
# primeiro elemento da coluna 2
my_array[0][1]

0.7326695078436829

In [55]:
# segundo elemento da segunda coluna
my_array[1][1]

0.798985353262283

In [56]:
# usando vírgula
my_array[1,1]

0.798985353262283

In [57]:
# imprimindo 3 valores
my_array[:3,1]

array([0.73266951, 0.79898535, 0.54180965])

In [58]:
# todas as linhas da coluna 2 multiplicado por 10
my_array[:,1] * 10

array([7.32669508, 7.98985353, 5.41809652, 5.53172685, 9.63408953,
       8.77878587, 9.16917511, 2.82324005, 7.14153386, 5.97748102])

In [59]:
# comparação (retorna os índices)
my_array > 0.50

array([[ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [ True, False],
       [False,  True],
       [False,  True]])

In [61]:
# extraindo os valores maiores
my_array[my_array > 0.50]

array([0.76046086, 0.73266951, 0.79898535, 0.8981312 , 0.54180965,
       0.82887902, 0.55317269, 0.60251293, 0.96340895, 0.87787859,
       0.91691751, 0.98790169, 0.71415339, 0.5977481 ])

## Carregar a partir de arquivos de texto ##

In [0]:
# Carregando
dataset = np.loadtxt('dataset_numeros.txt', delimiter=',')

In [63]:
dataset.shape

(6,)

In [64]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [0]:
#dividindo o arquivo
a, b, c = np.loadtxt('https://raw.githubusercontent.com/robsonpiere/ds-minerando-dados-exercicios/master/modulo_05/dataset_valores.txt', skiprows=1, unpack=True)

In [67]:
# array A
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [68]:
# array b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [69]:
# array c
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [0]:
# carregar arquivo pulando linhas
# converter o que não for inteiro em 0
url = 'https://raw.githubusercontent.com/robsonpiere/ds-minerando-dados-exercicios/master/modulo_05/dataset_valores_vazio.txt'
dataset = np.genfromtxt(url, skip_header=2, filling_values=0)

In [71]:
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])